FROM ubuntu:18.04
LABEL Name=networkworkshop Version=0.0.1
RUN echo "now building..."
RUN apt-get update && apt-get install -y iproute2 iputils-ping traceroute tcpdump dnsmasq python3 curl wget gawk dnsutils procps php
RUN echo "now running..."
